// DO NOT EDIT — auto-generated by scripts/build-info.ts during `npm run build`
export const BUILD_GIT_HASH = "9c1211a" as const;
export const BUILD_TIMESTAMP = "2026-08-05T10:22:39.096Z" as const;
export const BUILD_VERSION = "0.1.0" as const;
