// DO NOT EDIT — auto-generated by scripts/build-info.ts during `npm run build`
export const BUILD_GIT_HASH = "91c2906" as const;
export const BUILD_TIMESTAMP = "2026-08-06T14:59:56.974Z" as const;
export const BUILD_VERSION = "0.1.0" as const;
