// DO NOT EDIT — auto-generated by scripts/build-info.ts during `npm run build`
export const BUILD_GIT_HASH = "21b284f" as const;
export const BUILD_TIMESTAMP = "2026-08-05T10:11:15.242Z" as const;
export const BUILD_VERSION = "0.1.0" as const;
