/**
 * Generates static build-time constants (git hash + build timestamp)
 * consumed by the app at runtime. Run as:
 *
 *   tsx scripts/build-info.ts > app/build-info.ts
 *
 * next.config.mjs wires this into `next build`.
 */
import { execSync } from "child_process";
import { writeFileSync } from "fs";

const gitHash = execSync("git rev-parse --short HEAD", { encoding: "utf8" }).trim();

const buildTime = new Date().toISOString();

const out = `// DO NOT EDIT — auto-generated by scripts/build-info.ts during \`npm run build\`
export const BUILD_GIT_HASH = "${gitHash}" as const;
export const BUILD_TIMESTAMP = "${buildTime}" as const;
export const BUILD_VERSION = "${process.env.npm_package_version ?? "dev"}" as const;
`;

writeFileSync("app/build-info.ts", out);
console.log(`Wrote app/build-info.ts (hash=${gitHash}, time=${buildTime})`);
